### ISSUE TITLE
Example's log does not correspond to Draggable emitter?

### ISSUE THREAD

**Issue by ovvn** [lever/l-dragdrop#3]
In the example's dragCallback
```
  dragCallback: (evt, draggable, droppable) ->
    console.log("e, draggable, droppable", evt, draggable, droppable);
```
I got undefined for 'evt' due to https://github.com/lever/l-dragdrop/blob/master/index.coffee#L45
which seem to returning only draggable, droppable dom elements.

**Comment by enjalot** [comment]
you have to explicitly pass the `$event` in the template. event handlers in derby will pass in any arguments you give when you call them in the template, followed by all the arguments provided by the event emitter.

**Comment by enjalot** [comment]
the example is wrong tho, this line should be `on-drop=dragCallback($event)`
http://derbyjs.com/docs/derby-0.6/views/template-syntax/functions-and-events#dom-event-arguments

**Comment by ovvn** [comment]
```
this line should be on-drop=dragCallback($event)
```
Not sure it'll work with custom events, like on-drop in this case which is emitted in Droppable as follows:
```
onDrop = (itemEl) =>
    return unless itemEl && @_dropTarget
    @emit 'drop', itemEl, @_dropTarget
```

**Comment by enjalot** [comment]
oh, you're probably right. just a mistake on my part in the example then.

On Wed, May 13, 2015 at 8:36 AM, Osman Mazinov <notifications@github.com>
wrote:

> this line should be on-drop=dragCallback($event)
>
> Not sure it'll work with custom events, like on-drop in this case which is
> emitted in Droppable as follows:
>
> onDrop = (itemEl) =>
>     return unless itemEl && @_dropTarget
>     @emit 'drop', itemEl, @_dropTarget
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lever/l-dragdrop/issues/3#issuecomment-101718319>.
>



-- 
Ian Johnson - 周彦
http://enja.org
